modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Stalemated/s-lib/issues"
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "s_lib"
version = "${version}"
displayName = "S-Lib"
authors = "Stalemated"
description = '''
A core utility library providing shared code for Stalemated's mods.
'''
logoFile = "META-INF/icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/s-lib"

[[dependencies.s_lib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.s_lib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"